DROP TABLE IF EXISTS telefone;
DROP TABLE IF EXISTS usuario;

CREATE TABLE telefone (
  id NUMBER AUTO_INCREMENT  PRIMARY KEY,
  ddd VARCHAR(5) DEFAULT NULL,
  number VARCHAR(15) DEFAULT NULL
);

CREATE TABLE usuario (
  id NUMBER AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) DEFAULT NULL,
  email VARCHAR(250) DEFAULT NULL,
  password VARCHAR(250) DEFAULT NULL,
  token VARCHAR(250) DEFAULT NULL,
  created DATE DEFAULT NULL,
  modified DATE DEFAULT NULL,
  last_login DATE DEFAULT NULL
);